const seedDataByYear = [
    {
        year: 2022,
        data: [
            { variety: "BINA Dhan 11", UttarPradesh: 3 },
            { variety: "BINA Dhan 17", UttarPradesh: 3 },
            { variety: "BRRI Dhan 100", UttarPradesh: 2 },
            { variety: "BRRI Dhan 75", UttarPradesh: 2 },
            { variety: "BRRI Dhan 84", UttarPradesh: 2 },
            { variety: "MTU 1156", UttarPradesh: 3 },
            { variety: "Rajendra Saraswati", UttarPradesh: 3 },
            { variety: "Swarna Samriddhi", UttarPradesh: 3 },
        ],
        columns: ["variety", "Uttar Pradesh"],
        stateKeys: ["UttarPradesh"],
    },
    {
        year: 2023,
        data: [
            { variety: "Bauna kalanamak 102", Chhattisgarh: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 50, GrandTotal: 50 },
            { variety: "BINA Dhan 11", Chhattisgarh: 100, Odisha: 10, Telangana: 40, WestBengal: "", UttarPradesh: 74, GrandTotal: 224 },
            { variety: "BINA Dhan 17", Chhattisgarh: 10, Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 24, GrandTotal: 34 },
            { variety: "BPT 2782", Chhattisgarh: "", Odisha: 90, Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 90 },
            { variety: "BRRI Dhan 100", Chhattisgarh: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 4, GrandTotal: 4 },
            { variety: "BRRI Dhan 69", Chhattisgarh: "", Odisha: 220, Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 220 },
            { variety: "BRRI Dhan 75", Chhattisgarh: "", Odisha: 50, Telangana: "", WestBengal: "", UttarPradesh: 4, GrandTotal: 54 },
            { variety: "BRRI Dhan 84", Chhattisgarh: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 4, GrandTotal: 4 },
            { variety: "BRRI Dhan 99", Chhattisgarh: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 4, GrandTotal: 4 },
            { variety: "CG Devbhog", Chhattisgarh: 30, Odisha: 130, Telangana: 20, WestBengal: "", UttarPradesh: 180, GrandTotal: 360 },
            { variety: "CR Dhan 15", Chhattisgarh: "", Odisha: 200, Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 200 },
            { variety: "DRR Dhan 48", Chhattisgarh: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 20, GrandTotal: 20 },
            { variety: "DRR Dhan 50", Chhattisgarh: "", Odisha: 90, Telangana: "", WestBengal: "", UttarPradesh: 4, GrandTotal: 94 },
            { variety: "DRR Dhan 56", Chhattisgarh: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 4, GrandTotal: 4 },
            { variety: "DRR Dhan 58", Chhattisgarh: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 4, GrandTotal: 4 },
            { variety: "HUR 917", Chhattisgarh: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 100, GrandTotal: 100 },
            { "variety": "Kalanamak Kiran", "Chhattisgarh": "", "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": 50, "Grand Total": 50 },
            { "variety": "Kalanamak KN 3", "Chhattisgarh": "", "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": 50, "Grand Total": 50 },
            { "variety": "Kalanamak SL 03", "Chhattisgarh": "", "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": 100, "Grand Total": 100 },
            { "variety": "MTU 1156", "Chhattisgarh": 30, "Odisha": 800, "Telangana": 300, "West Bengal": 210, "Uttar Pradesh": 1070, "Grand Total": 1070 },
            { "variety": "MTU 1262", "Chhattisgarh": 60, "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": "", "Grand Total": 60 },
            { "variety": "PR 126", "Chhattisgarh": "", "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": 64, "Grand Total": 64 },
            { "variety": "Rajendra Mansuri-1", "Chhattisgarh": "", "Odisha": 90, "Telangana": "", "West Bengal": "", "Uttar Pradesh": "", "Grand Total": 90 },
            { "variety": "Rajendra Kasturi", "Chhattisgarh": "", "Odisha": 30, "Telangana": "", "West Bengal": "", "Uttar Pradesh": "", "Grand Total": 30 },
            { "variety": "Rajendra Saraswati", "Chhattisgarh": 20, "Odisha": 60, "Telangana": 60, "West Bengal": "", "Uttar Pradesh": "", "Grand Total": 140 },
            { "variety": "Ranjit Sub1", "Chhattisgarh": "", "Odisha": "", "Telangana": "", "West Bengal": 92, "Uttar Pradesh": "", "Grand Total": 92 },
            { "variety": "Sabour Harshit", "Chhattisgarh": "", "Odisha": "", "Telangana": "", "West Bengal": 92, "Uttar Pradesh": "", "Grand Total": 92 },
            { "variety": "Sabour Heera", "Chhattisgarh": "", "Odisha": "", "Telangana": "", "West Bengal": 92, "Uttar Pradesh": "", "Grand Total": 92 },
            { "variety": "Samba Mahsuri Sub 1", "Chhattisgarh": "", "Odisha": 40, "Telangana": "", "West Bengal": "", "Uttar Pradesh": "", "Grand Total": 40 },
            { "variety": "Swarna Samriddhi", "Chhattisgarh": 20, "Odisha": 665, "Telangana": 205, "West Bengal": 300, "Uttar Pradesh": 105, "Grand Total": 1055 },
            { "variety": "Swarna Shakti Dhan", "Chhattisgarh": 100, "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": 100, "Grand Total": 100 },
            { "variety": "Swarna Shreya", "Chhattisgarh": "", "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": 15, "Grand Total": 15 },
            { "variety": "Swarna-Sub1", "Chhattisgarh": "", "Odisha": "", "Telangana": "", "West Bengal": 20, "Uttar Pradesh": 115, "Grand Total": 115 },
            { "variety": "Tripura Hakuchuk 2", "Chhattisgarh": 60, "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": "", "Grand Total": 60 },
            { "variety": "Uttar Samir", "Chhattisgarh": "", "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": 40, "Grand Total": 40 },
            { "variety": "Grand Total", "Chhattisgarh": 100, "Odisha": 3337, "Telangana": 100, "West Bengal": 90, "Uttar Pradesh": 1315, "Grand Total": 4942 }
        ],
        columns: ["variety", "Chhattisgarh", "Odisha", "Telangana", "West Bengal", "Uttar Pradesh", "Grand Total"],
        stateKeys: ["Chhattisgarh", "Odisha", "Telangana", "WestBengal", "UttarPradesh", "GrandTotal"],
    },

    {
        year: 2024,
        data: [
            { "variety": "ADT 56", "Assam": "", "Bihar": "", "Chhattisgarh": "", "Jharkhand": "", "Odisha": "", "Telangana": 10, "West Bengal": "", "Uttar Pradesh": "", "Grand Total": 10 },
            { "variety": "Bauna kalanamak 102", "Assam": "", "Bihar": "", "Chhattisgarh": "", "Jharkhand": "", "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": 50, "Grand Total": 50 },
            { "variety": "BINA Dhan 11", "Assam": "", "Bihar": "", "Chhattisgarh": "", "Jharkhand": "", "Odisha": 100, "Telangana": "", "West Bengal": "", "Uttar Pradesh": 20, "Grand Total": 120 },
            { "variety": "BINA Dhan 17", "Assam": "", "Bihar": "", "Chhattisgarh": 50, "Jharkhand": 20, "Odisha": 10, "Telangana": "", "West Bengal": "", "Uttar Pradesh": 14, "Grand Total": 94 },
            { "variety": "BRRI Dhan 100", "Assam": "", "Bihar": "", "Chhattisgarh": "", "Jharkhand": "", "Odisha": 30, "Telangana": "", "West Bengal": 220, "Uttar Pradesh": 74, "Grand Total": 324 },
            { "variety": "BRRI Dhan 75", "Assam": "", "Bihar": "", "Chhattisgarh": "", "Jharkhand": "", "Odisha": 10, "Telangana": "", "West Bengal": "", "Uttar Pradesh": 74, "Grand Total": 324 },
            { "variety": "BRRI Dhan 84", "Assam": "", "Bihar": "", "Chhattisgarh": "", "Jharkhand": "", "Odisha": 30, "Telangana": "", "West Bengal": 100, "Uttar Pradesh": 84, "Grand Total": 224 },
            { "variety": "BRRI Dhan 99", "Assam": "", "Bihar": "", "Chhattisgarh": "", "Jharkhand": "", "Odisha": "", "Telangana": "", "West Bengal": 60, "Uttar Pradesh": 80, "Grand Total": 140 },
            { "variety": "CGZR-2", "Assam": "", "Bihar": "", "Chhattisgarh": "", "Jharkhand": "", "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": 30, "Grand Total": 30 },
            { "variety": "CR Dhan 307", "Assam": "", "Bihar": "", "Chhattisgarh": "", "Jharkhand": "", "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": 5, "Grand Total": 5 },
            { "variety": "CR Dhan 320", "Assam": "", "Bihar": "", "Chhattisgarh": "", "Jharkhand": "", "Odisha": "", "Telangana": "", "West Bengal": "", "Uttar Pradesh": 5, "Grand Total": 5 },
            { "variety": "CR Dhan 414", "Assam": "", "Bihar": "", "Chhattisgarh": "", "Jharkhand": "", "Odisha": "", "Telangana": 4, "West Bengal": "", "Uttar Pradesh": "", "Grand Total": 4 },
            { "variety": "DRR Dhan 42", "Assam": "", "Bihar": "", "Chhattisgarh": "", "Jharkhand": "", "Odisha": 20, "Telangana": "", "West Bengal": 4, "Uttar Pradesh": "", "Grand Total": 24 },
            { variety: "DRR Dhan 48", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: 280, Telangana: "", WestBengal: "", UttarPradesh: 24, GrandTotal: 304 },
            { variety: "DRR Dhan 53", Assam: "", Bihar: "", Chhattisgarh: 30, Jharkhand: 10, Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 90, GrandTotal: 130 },
            { variety: "DRR Dhan 56", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: 230, Telangana: "", WestBengal: "", UttarPradesh: 34, GrandTotal: 264 },
            { variety: "DRR Dhan 58", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: 150, Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 150 },
            { variety: "DRR Dhan 63", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: 105, Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 105 },
            { variety: "HUR 917", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 30, GrandTotal: 30 },
            { variety: "IR 64 Sub1", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: 10, Odisha: "", Telangana: "", WestBengal: 10, UttarPradesh: 90, GrandTotal: 110 },
            { variety: "Kalanamak Kiran", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 50, GrandTotal: 50 },
            { variety: "KN 3", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 50, GrandTotal: 50 },
            { variety: "MTU 1010", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 180, GrandTotal: 180 },
            { variety: "MTU 1156", Assam: "", Bihar: "", Chhattisgarh: 30, Jharkhand: 10, Odisha: 15, Telangana: "", WestBengal: "", UttarPradesh: 43, GrandTotal: 98 },
            { variety: "MTU 1271", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 50, GrandTotal: 50 },
            { variety: "MTU 1293", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 60, GrandTotal: 60 },
            { variety: "MTU 1321", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 40, GrandTotal: 40 },
            { variety: "NLR 3354", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 10, GrandTotal: 69 },
            { variety: "NLR 4001", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 30, GrandTotal: 5 },
            { variety: "NLR 40054", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 10, GrandTotal: 60 },
            { variety: "PR 126", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: 10, Odisha: 234, Telangana: "", WestBengal: "", UttarPradesh: 176, GrandTotal: 420 },
            { variety: "PR 130", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 48, GrandTotal: 48 },
            { variety: "Protezin", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 100, GrandTotal: 100 },
            { variety: "Pusa Kalanamak CRD-2", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 60, GrandTotal: 60 },
            { variety: "Rajendra Saraswati", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 10, GrandTotal: 10 },
            { variety: "Ratnagiri 8", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: 20, Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 44, GrandTotal: 64 },
            { variety: "Swarna Samriddhi", Assam: "", Bihar: "", Chhattisgarh: 50, Jharkhand: 50, Odisha: 210, Telangana: 15, WestBengal: "", UttarPradesh: 10, GrandTotal: 335 },
            { variety: "Swarna Shakti Dhan", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: 190, Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 190 },
            { variety: "Swarna Shreya", Assam: "", Bihar: "", Chhattisgarh: 35, Jharkhand: 20, Odisha: 10, Telangana: "", WestBengal: "", UttarPradesh: 245, GrandTotal: 310 },
            { variety: "Swarna Sukha Dhan", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: 25, Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 25 },
            { variety: "Swarna Unnat Dhan", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: 100, Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 100 },
            { variety: "Swarna-Sub1", Assam: 40, Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 40 },
            { variety: "Telangana Sona", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: 20, Telangana: "", WestBengal: 60, UttarPradesh: "", GrandTotal: 80 },
            { variety: "Tripura Hakuchuk 2", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: 10, Odisha: 30, Telangana: "", WestBengal: 4, UttarPradesh: "", GrandTotal: 44 },
            { variety: "Uttar Ganga", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 30, GrandTotal: 30 },
            { variety: "Uttar Lakshmi", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 150, GrandTotal: 150 },
            { variety: "Uttar Samir", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 30, GrandTotal: 30 },
            { variety: "Uttar Sona", Assam: "", Bihar: "", Chhattisgarh: 15, Jharkhand: "", Odisha: 120, Telangana: 10, WestBengal: "", UttarPradesh: 44, GrandTotal: 189 },
            { variety: "Zinco Rice MS", Assam: "", Bihar: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Telangana: "", WestBengal: "", UttarPradesh: 100, GrandTotal: 100 },
            { variety: "Grand Total", Assam: 100, Bihar: 180, Chhattisgarh: 180, Jharkhand: 20, Odisha: 3907, Telangana: 30, WestBengal: 55, UttarPradesh: 1237, GrandTotal: 5709 },
        ],
        columns: ["variety", "Assam", "Bihar", "Chhattisgarh", "Jharkhand", "Odisha", "Telangana", "West Bengal", "Uttar Pradesh", "Grand Total"],
        stateKeys: ["Assam", "Bihar", "Chhattisgarh", "Jharkhand", "Odisha", "Telangana", "West Bengal", "Uttar Pradesh", "GrandTotal"],
    },

    {
        year: 2025,
        data: [
            { variety: "Bauna kalanamak 102", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 14, GrandTotal: 14 },
            { variety: "BINA Dhan 11", Assam: 30, Chhattisgarh: 30, Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 3, GrandTotal: 63 },
            { variety: "BINA Dhan 17", Assam: "", Chhattisgarh: 60, Jharkhand: 15, Odisha: 20, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 40, GrandTotal: 135 },
            { variety: "BRRI Dhan 100", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: 50, UttarPradesh: 40, GrandTotal: 90 },
            { variety: "BRRI Dhan 75", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 64, GrandTotal: 64 },
            { variety: "BRRI Dhan 84", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: 30, UttarPradesh: 34, GrandTotal: 64 },
            { variety: "BRRI Dhan 99", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: 30, UttarPradesh: 10, GrandTotal: 40 },
            { variety: "CG Devbhog", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: 25, UttarPradesh: 30, GrandTotal: 55 },
            { variety: "CR Dhan 107", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 90, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 90 },
            { variety: "CR Dhan 320", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 80, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 80 },
            { variety: "CR Dhan 804", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 210, Rajasthan: 30, Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 240 },
            { variety: "CR Dhan 808", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 80, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 80 },
            { variety: "DRR Dhan 42", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 30, Rajasthan: 10, Telangana: "", WestBengal: 16, UttarPradesh: "", GrandTotal: 56 },
            { variety: "DRR Dhan 45", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 55, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 55 },
            { variety: "DRR Dhan 48", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 60, Rajasthan: 10, Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 70 },
            { variety: "DRR Dhan 56", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 45, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 30, GrandTotal: 75 },
            { variety: "DRR Dhan 58", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 40, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 4, GrandTotal: 44 },
            { variety: "DRR Dhan 63", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 20, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 4, GrandTotal: 24 },
            { variety: "DRR Dhan 79", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 2, GrandTotal: 2 },
            { variety: "Kalanamak Kiran", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 24, GrandTotal: 24 },
            { variety: "Kalanamak KN 3", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 8, GrandTotal: 8 },
            { variety: "MTU 1156", Assam: "", Chhattisgarh: 20, Jharkhand: "", Odisha: "", Rajasthan: 10, Telangana: "", WestBengal: 62, UttarPradesh: "", GrandTotal: 92 },
            { variety: "NLR 3354", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 30, Rajasthan: 50, Telangana: "", WestBengal: 124, UttarPradesh: "", GrandTotal: 204 },
            { variety: "NLR 40054", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 10, Rajasthan: 10, Telangana: "", WestBengal: 60, UttarPradesh: "", GrandTotal: 80 },
            { variety: "PR 126", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 30, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 188, GrandTotal: 218 },
            { variety: "PR 131", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 72, GrandTotal: 72 },
            { variety: "Protezin", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 60, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 60 },
            { variety: "Rajendra Saraswati", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 50, GrandTotal: 50 },
            { variety: "Ratnagiri 8", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 20, Rajasthan: 15, Telangana: "", WestBengal: 40, UttarPradesh: "", GrandTotal: 75 },
            { variety: "Sabour Mahsuri", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 2, GrandTotal: 2 },
            { variety: "Samba-Sub1", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 50, GrandTotal: 50 },
            { variety: "Swarna Samriddhi", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 240, Rajasthan: 50, Telangana: "", WestBengal: 30, UttarPradesh: 50, GrandTotal: 370 },
            { variety: "Swarna Shakti Dhan", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 120, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 120 },
            { variety: "Swarna Shreya", Assam: "", Chhattisgarh: 40, Jharkhand: "", Odisha: 200, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 45, GrandTotal: 285 },
            { variety: "Swarna Sukha Dhan", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 80, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 80 },
            { variety: "Telangana Sona", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 255, Rajasthan: 30, Telangana: "", WestBengal: 94, UttarPradesh: "", GrandTotal: 379 },
            { variety: "Tripura Hakchuk 2", Assam: "", Chhattisgarh: 30, Jharkhand: "", Odisha: "", Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: 30, GrandTotal: 60 },
            { variety: "Uttar Sona", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 30, Rajasthan: 30, Telangana: 20, WestBengal: 6, UttarPradesh: "", GrandTotal: 86 },
            { variety: "Zinco Rice MS", Assam: "", Chhattisgarh: "", Jharkhand: "", Odisha: 60, Rajasthan: "", Telangana: "", WestBengal: "", UttarPradesh: "", GrandTotal: 60 },
            { variety: "Grand Total", Assam: 90, Chhattisgarh: 65, Jharkhand: 40, Odisha: 2030, Rajasthan: 60, Telangana: 190, WestBengal: 45, UttarPradesh: 1196, GrandTotal: 3716 },
        ],
        columns: ["variety", "Assam", "Chhattisgarh", "Jharkhand", "Odisha", "Rajasthan", "Telangana", "West Bengal", "Uttar Pradesh", "Grand Total"],
        stateKeys: ["Assam", "Chhattisgarh", "Jharkhand", "Odisha", "Rajasthan", "Telangana", "West Bengal", "Uttar Pradesh", "GrandTotal"],
    }


];


export default seedDataByYear